create TABLE IF NOT EXISTS VIDEO (id BIGINT AUTO_INCREMENT,
title VARCHAR2 (50) NOT NULL,
description VARCHAR2 (500) NOT NULL,
tags VARCHAR2 (500) NOT NULL,
author VARCHAR2 (50) NOT NULL,
url VARCHAR2 (1000) NOT NULL,
create_time TIMESTAMP,
update_time TIMESTAMP,
) ;